/**
  * convgerber Convert Protel Autrax gerber to new format
  *
  * Written and maintained by Robert Murphy [ robert.murphy@gmx.com ]
  *
  * This purpose of this program to convert the gerber file generated by
  * Protel Autotrax to a newer format readable by FlatCAM & Gerbv
  *
  * Code logic based on hpgl-distiller by Paul L Daniels
  * 
  * Original version written: Tuesday 22 Nov 2016
  *
  *
  * Process description:
  *
  * convgerber -i src_filename -o dest_filename
  *
  **/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <errno.h>

#define BS 0x08
#define LF 0x0A
#define FF 0x0C
#define CR 0x0D
#define SPACE 0x20
#define GERBER_TERM 0x2A

#define GCONV_VERSION "0.0.1"
char  GCONV_HEADER[] = "G04 This is a Protel Autotrax gerber file converted by *\n"
					   "G04 convgerber V-0.0.1 *\n"
					   "G04 More information is available about convgerber at *\n"
                       "G04 https://github.com/ozzyrob/convgerber *\n"
                       "G04 --End of header info--*\n"
                       "%MOIN*%\n"
                       "%FSLAX23Y23*%\n"
                       "%IPPOS*%";
char GCONV_FILE_SIG[] = "X0Y0*";                       
char APT_LIST_START[] = "G04 APERTURE LIST*\n";
char APT_LIST_END[] = "G04 APERTURE END LIST*\n";
char LAYER_POLARITY_DARK[] = "G04 Set Layer Polarity to dark*\n%LPD*%";
char LAYER_POLARITY_CLEAR[] = "G04 Set Layer Polarity to dark*\n%LPC*%";
             
                       
char GCONV_HELP[]="convgerber: Protel gerber file converter\n"
	"Written by Robert Murphy.\n"
	"This software is available at https://github.com/ozzyrob/convgerber\n"
	"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\n"
	"\n"
	"This is free software; you are free to change and redistribute it.\n"
	"There is NO WARRANTY, to the extent permitted by law.\n"
	"\n"
	"Usage: convgerber -i <input GERBER> -o <output file> [-v] [-h]\n"
	"\n"
	"\t-i <input GERBER> : Specifies which file contains the gerber file to convert.\n"
	"\t-o <output file> : specifies which file the converted gerber is to be saved to.\n"
	"\n"
	"\t-v : Display current software version\n"
	"\t-h : Display this help.\n"
	"\n";

struct gconv_glb {
	int status;
	char *input_filename;
	char *output_filename;
	char *aperture_filename;
};                       

/**
  * GCONV_show_version
  *
  * Display the current convgerber version
  */
int GCONV_show_version( struct gconv_glb *glb ) {
	fprintf(stderr,"%s\n", GCONV_VERSION);
	return 0;
}

/**
  * GCONV_show_help
  *
  * Display the help data for this program
  */
int GCONV_show_help( struct gconv_glb *glb ) {
	GCONV_show_version(glb);
	fprintf(stderr,"%s\n", GCONV_HELP);

	return 0;

}

/**
  * GCONV_init
  *
  * Initializes any variables or such as required by
  * the program.
  */
int GCONV_init( struct gconv_glb *glb )
{
	glb->status = 0;
	glb->input_filename = NULL;
	glb->output_filename = NULL;
	glb->aperture_filename = "aperture.dat";

	return 0;
}

/**
  * GCONV_write_header
  *
  * Writer header to converted gerber file
  * 
  */
int GCONV_write_header( FILE *fo )
{
	fprintf(fo,"%s\n", GCONV_HEADER);

	return 0;
}
/**
  * GCONV_set_layer_dark
  *
  * Set Layer Polarity to dark
  * 
  */
int GCONV_set_layer_dark( FILE *fo )
{
	fprintf(fo,"%s\n", LAYER_POLARITY_DARK);

	return 0;
}

/**
  * GCONV_set_layer_clear
  *
  * Set Layer Polarity to clear
  * 
  */
int GCONV_set_layer_clear( FILE *fo )
{
	fprintf(fo,"%s\n", LAYER_POLARITY_CLEAR);

	return 0;
}

/**
  * GCONV_check_input_file
  *
  * Check if input file is a Protel file
  * First 5 bytes should be "X0Y0*"
  * Last byte should be BS (0x08)
  * 
  */
int GCONV_check_input_file( FILE *fi )
{
	char file_sig[6];
//* File should start with X0Y0*
	fgets( file_sig, 6, fi);
	fseek (fi, 0, SEEK_SET);
	return ( strcmp ( GCONV_FILE_SIG, file_sig ) );
}

/**
  * GCONV_write_apperatures
  *
  * Writer header to converted gerber file
  * 
  */
int GCONV_write_apertures( FILE *fo, FILE *fa )
{
		int aperture_read;
		fprintf( fo, APT_LIST_START );
		
		while (  ( aperture_read = fgetc(fa) ) != EOF ) { 
			
			fputc( aperture_read, fo );
		}
		fprintf( fo, APT_LIST_END );
	return 0;
}
/**
  * GCONV_parse_parameters
  *
  * Parses the command line parameters and sets the
  * various convgerber settings accordingly
  */
int GCONV_parse_parameters( int argc, char **argv, struct gconv_glb *glb )
{

	char c;

	do {
		c = getopt(argc, argv, "I:i:o:vh");
		switch (c) { 
			case EOF: /* finished */
				break;

			case 'i':
				glb->input_filename = strdup(optarg);
				break;

			case 'o':
				glb->output_filename = strdup(optarg);
				break;


			case 'h':
				GCONV_show_help(glb);
				exit(1);
				break;

			case 'v':
				GCONV_show_version(glb);
				exit(1);
				break;

			case '?':
				break;

			default:
				fprintf(stderr, "internal error with getopt\n");
				exit(1);
				
		} /* switch */
	} while (c != EOF); /* do */
	return 0;
}

/**
  * convgerber,  main body
  *
  * This program inputs an existing Protel Autotrax Gerber file which
  * does not conform with later formats
  */
int main(int argc, char **argv) {

	struct gconv_glb glb;
	FILE *fi, *fo, *fa;
	int gerber_read;
	int file_check;
	int curr_pos;
	
	/* Initialize our global data structure */
	GCONV_init(&glb);


	/* Decyper the command line parameters provided */
	GCONV_parse_parameters(argc, argv, &glb);

	/* Check the fundamental sanity of the variables in
		the global data structure to ensure that we can
		actually perform some meaningful work
		*/
	if ((glb.input_filename == NULL)) {
		fprintf(stderr,"Error: Input filename is NULL.\n");
		exit(1);
	}
	if ((glb.output_filename == NULL)) {
		fprintf(stderr,"Error: Output filename is NULL.\n");
		exit(1);
	}
	
	/* Attempt to open input file as read only
	 */ 
	fi = fopen(glb.input_filename,"r");
	if (!fi) {
		fprintf(stderr,"Error: Cannot open input file '%s' for reading (%s)\n", glb.input_filename, strerror(errno));
		return 3;
	}
	
	/* Check if input file has a valid signature first 5 chars X0Y0*
	 */
	file_check = GCONV_check_input_file( fi );
	if  ( file_check != 0 )  {
		fprintf( stderr, "Error: %s does not appear to be a valid Autotrax gerber file\n", glb.input_filename );
		return 6;
	}
	
	/* Attempt to open the aperture file as read-only 
	 */
	fa = fopen(glb.aperture_filename,"r");
	if (!fa) {
		fprintf(stderr,"Error: Cannot open aperture data file '%s' for reading (%s)\n", glb.aperture_filename, strerror(errno));
		return 4;
	}

	/* Attempt to open the output file in write mode
		(no appending is done, any existing file will be
		overwritten
		*/
	fo = fopen(glb.output_filename,"w");
	if (!fo) {
		fprintf(stderr,"Error: Cannot open output file '%s' for writing (%s)\n", glb.output_filename, strerror(errno));
		return 5;
	}
	

	GCONV_write_header (fo);
	GCONV_write_apertures(fo ,fa);
	GCONV_set_layer_dark(fo);
	
	//* Read source file a character at a time
		 while (  ( gerber_read = fgetc(fi) ) != EOF ) {
				

				switch (gerber_read) {
					
//* If we have "*" write "*\n" to destination file					
					case GERBER_TERM:
						fprintf(fo, "*\n"); 
						break;
//* Ignore Backspace, Line feed (newline), Form feed, Carriage return & space
					case BS :
					case LF :
					case FF :
					case CR :
					case SPACE :
						break;
//* Write X,Y, cordinates, D-codes, to destination file
//* Should check for "illegal characters"
					case 'X' :
					case 'Y' :
					case 'M' :
					case 'D' :
					case '0' :
					case '1' :
					case '2' :
					case '3' :
					case '4' :
					case '5' :
					case '6' :
					case '7' :
					case '8' :
					case '9' :
						fputc( gerber_read, fo );
						break;
					default :
						curr_pos=(ftell(fi) -1);
						fprintf( stderr, "Error: Illegal character found.\n Hex value = 0x%.2x\n At position 0x%.8x\n", gerber_read, curr_pos);
						return 7;
					}
			}
	fclose(fo);
	fclose(fi);
	fclose(fa);
	printf("Autotrax file successfully converted\n");
	return 0;
}	
